# Generated by Django 3.2 on 2021-06-15 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete_PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=255, verbose_name='Процеоср')),
                ('videoCard', models.CharField(max_length=255, verbose_name='Відео карта')),
                ('ram', models.CharField(max_length=255, verbose_name='Оперативна пам"ять')),
                ('memory', models.CharField(max_length=255, verbose_name='Внутрішній накопичувач')),
                ('mainBoard', models.CharField(max_length=255, verbose_name='Материнська плата')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('img', models.ImageField(upload_to='', verbose_name='Зображення')),
                ('link', models.TextField(default='', verbose_name='Посилання на товар')),
            ],
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('product_img1', models.ImageField(upload_to='')),
                ('product_description', models.TextField(max_length=5000, null=True)),
                ('product_price', models.IntegerField()),
                ('product_guarantee', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product_category')),
            ],
        ),
        migrations.CreateModel(
            name='add_to_cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
