# Generated by Django 3.2 on 2021-06-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='product_guarantee',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='quantity',
        ),
    ]
