# Generated by Django 3.1.6 on 2021-03-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.TextField(verbose_name='Ссылка на товар'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='price',
            field=models.TextField(verbose_name='Ссылка на товар'),
        ),
    ]
