# Generated by Django 3.1.6 on 2021-03-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cooler_hdd_mainboard_powersupplyunit_ram_ssd_videocard'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.TextField(default='Опис товару'),
        ),
        migrations.AddField(
            model_name='cooler',
            name='description',
            field=models.TextField(default='Опис товару'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='description',
            field=models.TextField(default='Опис товару'),
        ),
        migrations.AddField(
            model_name='hdd',
            name='description',
            field=models.TextField(default='Опис товару'),
        ),
        migrations.AddField(
            model_name='mainboard',
            name='description',
            field=models.TextField(default='Опис товару'),
        ),
        migrations.AddField(
            model_name='powersupplyunit',
            name='description',
            field=models.TextField(default='Опис товару'),
        ),
        migrations.AddField(
            model_name='ram',
            name='description',
            field=models.TextField(default='Опис товару'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='description',
            field=models.TextField(default='Опис товару'),
        ),
        migrations.AddField(
            model_name='videocard',
            name='description',
            field=models.TextField(default='Опис товару'),
        ),
        migrations.AlterField(
            model_name='case',
            name='link',
            field=models.TextField(default='Посилання на товар', verbose_name='Посилання на товар'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='link',
            field=models.TextField(default='Посилання на товар', verbose_name='Посилання на товар'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='link',
            field=models.TextField(default='Посилання на товар', verbose_name='Посилання на товар'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='link',
            field=models.TextField(default='Посилання на товар', verbose_name='Посилання на товар'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='link',
            field=models.TextField(default='Посилання на товар', verbose_name='Посилання на товар'),
        ),
        migrations.AlterField(
            model_name='powersupplyunit',
            name='link',
            field=models.TextField(default='Посилання на товар', verbose_name='Посилання на товар'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='link',
            field=models.TextField(default='Посилання на товар', verbose_name='Посилання на товар'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='link',
            field=models.TextField(default='Посилання на товар', verbose_name='Посилання на товар'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='link',
            field=models.TextField(default='Посилання на товар', verbose_name='Посилання на товар'),
        ),
    ]
