# Generated by Django 3.2 on 2021-05-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210315_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(default='', verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='case',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
    ]
