# Generated by Django 3.2 on 2021-05-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210514_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooler',
            name='description',
            field=models.TextField(default='', verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='description',
            field=models.TextField(default='', verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='description',
            field=models.TextField(default='', verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='description',
            field=models.TextField(default='', verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='mainboard',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='powersupplyunit',
            name='description',
            field=models.TextField(default='', verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='powersupplyunit',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='powersupplyunit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='powersupplyunit',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='description',
            field=models.TextField(default='', verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='description',
            field=models.TextField(default='', verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='description',
            field=models.TextField(default='', verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
    ]
