# Generated by Django 3.2 on 2021-05-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210514_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete_PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=255, verbose_name='Процеоср')),
                ('videoCard', models.CharField(max_length=255, verbose_name='Відео карта')),
                ('ram', models.CharField(max_length=255, verbose_name='Оперативна пам"ять')),
                ('memory', models.CharField(max_length=255, verbose_name='Внутрішній накопичувач')),
                ('mainBoard', models.CharField(max_length=255, verbose_name='Материнська плата')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('img', models.ImageField(upload_to='', verbose_name='Зображення')),
            ],
        ),
    ]
