# Generated by Django 3.2 on 2021-05-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_complete_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete_pc',
            name='link',
            field=models.TextField(default='', verbose_name='Посилання на товар'),
        ),
    ]
